# Custom latexindent settings (overrides defaults)

defaultIndent: "  "

removeTrailingWhitespace:
    afterProcessing: 1

noAdditionalIndent:
    document: 1
    widepage: 1
    comment: 1

noAdditionalIndentGlobal:
    commands: 1

indentAfterItems:
    itemize: 1
    enumerate: 1
    description: 1
    list: 1
    inline: 1
    inlinin: 1
    inlinex: 1

lookForAlignDelims:
    tabular:
        delims: 1
        alignDoubleBackSlash: 1
        spacesBeforeDoubleBackSlash: 1
        spacesBeforeAmpersand: 1
        spacesAfterAmpersand: 1
        justification: "left"
    listabla: 1

modifyLineBreaks:
    preserveBlankLines: 1
    condenseMultipleBlankLinesInto: 1
    textWrapOptions:
        columns: 78
    environments:
        BeginStartsOnOwnLine: 1
        BodyStartsOnOwnLine: 1
        EndStartsOnOwnLine: 1
    items:
        ItemStartsOnOwnLine: 1
